# Generated by Django 4.1.7 on 2023-03-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0003_alter_moviedetails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetails',
            name='movie_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
